### ISSUE TITLE
Add rationale for the integrated PSU?

### ISSUE THREAD

**Issue by alexanderkjeldaas** [opencomputeproject/Project_Olympus#12]
First post!

No seriously, I wonder if you could add rationales for some of the design decisions.  For example the integrated PSU. What are the pros and cons for the integrated PSU?  How does it compare to a 12V power shelf as in open19.org? What does the cost look like?  How about redundancy?

**Comment by MarkShawMSFT** [comment]
Hi, thanks for your post.  As a Hardware guy, I'm new to GitHub and just noticed these two issues.

One of the things we learned with our earlier OCP releases is that time to market is faster when you have independence.  It's really flexibility and modularity leading to better interoperability.  We can mix high wattage and low wattage modules provisioning only the power necessary with only necessary costs.

Eliminating shared DC power eliminates a large single point of failure.  In the Project Olympus PMDU, we transmit N+N three phase power.  Any feed, any phase can fault anywhere from the DC distribution down to the server with the result that the server stays up and running.

Power shelves I've looked at also tend to consume precious U-height.
