### ISSUE TITLE
PDU Design?

### ISSUE THREAD

**Issue by chiuarthur** [opencomputeproject/Project_Olympus#13]
According to Mr. Vaid's blog post (https://azure.microsoft.com/en-us/blog/microsoft-reimagines-open-source-cloud-hardware/), MSFT also released the spec of the PDU. But I could not find it here on Github. Can someone help me?

**Comment by MarkShawMSFT** [comment]
We're working out the full details on open sourcing the hardware.  We ran into some initial issues with GitHub not allowing our big CAD files to be loaded.  Thus we only released the Universal Motherboard and server spec and CAD to start with.

We'll be releasing a large set of specs and some more CAD by mid December.  The PMDU spec will be included in that.
